In [ ]:
# NumPy – Python-da sürətli hesablamalar aparmaq üçün istifadə olunan kitabxanadır.
# Onun əsas obyekti ndarray adlı massivdir.

In [ ]:
# NumPy array — Python listindən daha sürətli və daha az yaddaş yeyən massivdir.

In [ ]:
import numpy as np

In [ ]:
np.zeros((3,3)) # 0dan ibaret

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))  #1lerden ibaret

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(0,10,2)  # 0-dan 10-a qədər, step=2

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,5) # 0-dan 1-ə  5 bərabər parçaya böl

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a1=np.array([1,2,3,6,7])
a1

array([1, 2, 3, 6, 7])

In [ ]:
a1[1]

np.int64(2)

In [ ]:
a1[1:4]

array([2, 3, 6])

In [ ]:
a1[-1]

np.int64(7)

In [ ]:
a1.ndim #arrayin olculerinin sayi 1D(1olculu arraydir)

1

In [ ]:
a1.shape #her olcude element sayi

(5,)

In [ ]:
a1.dtype #array elementlerinin tipi

dtype('int64')

In [ ]:
type(a1) #obyektin novunu gosterir

numpy.ndarray

In [ ]:
a1.size #element sayi

5

In [ ]:
a2=np.array([[1,2,3],
            [4,5,6]])
a2.ndim,a2.shape,a2.dtype,type(a2),a2.size

(2, (2, 3), dtype('int64'), numpy.ndarray, 6)

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2[0, 1]

np.int64(2)

In [ ]:
a2[:, 1]

array([2, 5])

In [ ]:
a2[1, :]

array([4, 5, 6])

In [ ]:
a2[:,2]

array([3, 6])

In [ ]:
a2[a2 > 5]

array([6])

In [ ]:
a3=np.array([[[1,2,3],
            [4,5,6]],

            [[3,5,6],
             [4,7,8]]])
a3.ndim,a3.shape,a3.dtype,type(a3),a3.size

(3, (2, 2, 3), dtype('int64'), numpy.ndarray, 12)

In [ ]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 5, 6],
        [4, 7, 8]]])

In [ ]:
# shape(bloklar, sətirlər, sütunlar)

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(5,3)) #randint(1, 10, size=(5,3)) → 1-dən 9-a qədər təsadüfi ədədlər ilə 5×3 ölçülü array yaradır.
random_arr

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5]])

In [ ]:
random_arr[:4,2]

array([6, 2, 3, 3])

In [ ]:
random_arr[1:,1]

array([1, 7, 6, 3])

In [ ]:
a = np.arange(6)   # [0 1 2 3 4 5]
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(2,5,5))#1-dən 9-a qədər təsadüfi ədədlərlə 3D array yaradır
random_arr

array([[[6, 9, 6, 1, 1],
        [2, 8, 7, 3, 5],
        [6, 3, 5, 3, 5],
        [8, 8, 2, 8, 1],
        [7, 8, 7, 2, 1]],

       [[2, 9, 9, 4, 9],
        [8, 4, 7, 6, 2],
        [4, 5, 9, 2, 5],
        [1, 4, 3, 1, 5],
        [3, 8, 8, 9, 7]]])

In [ ]:
random_arr[1,1,1:4]

array([4, 7, 6])

In [ ]:
random_arr[:,1:3,2]

array([[7, 5],
       [7, 9]])

In [ ]:
random_arr[:, 3:, 3]

array([[8, 2],
       [1, 9]])

In [ ]:
a1

array([1, 2, 3, 6, 7])

In [ ]:
a1*[2,2,2,2,2]

array([ 2,  4,  6, 12, 14])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2.shape,a2.T.shape

((2, 3), (3, 2))

In [ ]:
a2@a2.T  # 1*1+2*2+3*3,1*4,2*5,3*6

array([[14, 32],
       [32, 77]])

In [ ]:
np.dot(a2,a2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
np.matmul(a2,a2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
import time

start = time.time()
arr = np.random.randint(1, 10, size = (1_000_0000))
result = arr ** 10

end = time.time()

end - start


0.29439783096313477

In [ ]:

start = time.time()

result = []
for i in range(1_000_0000):
    result.append(i ** 10)

end = time.time()

end - start

3.196584939956665

In [ ]:
3.196584939956665/0.29439783096313477

10.858045147611666

In [ ]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 5, 6],
        [4, 7, 8]]])

In [ ]:
np.sum(a3)

np.int64(54)

In [ ]:
sum(a3)

array([[ 4,  7,  9],
       [ 8, 12, 14]])